/* eslint-disable */
// This file is auto-generated by `intent-compiler compile-intent`.

export const compiledIntentManifest = {
  "version": 1,
  "generatedAt": "2026-04-21T21:49:46.794Z",
  "dialect": "postgresql",
  "provider": "stub",
  "model": "gpt-4.1-mini",
  "context": {
    "projectName": "react-rest-drizzle-postgres",
    "orm": "drizzle",
    "apiArchitecture": "rest",
    "intentCount": 1,
    "schemaSnippetCount": 2
  },
  "intents": [
    {
      "id": "2940a96c89ac10d0ee0dea77",
      "key": "2940a96c89ac10d0ee0dea77",
      "sourceType": "code",
      "sourcePath": "src/server/index.ts",
      "line": 76,
      "prompt": "Find active users in <country> who signed up after <afterDate> and include their order count and total spend.",
      "placeholderPrompt": "Find active users in $1 who signed up after $2 and include their order count and total spend.",
      "paramExpressions": [
        "country",
        "afterDate"
      ],
      "sql": "-- TODO: replace stub with provider-backed SQL\n-- intent: Find active users in $1 who signed up after $2 and include their order count and total spend.",
      "dialect": "postgresql",
      "providerMode": "stub"
    }
  ]
} as const;

export type CompiledIntentMap = Record<string, { id: string; sql: string; dialect: string }>;

export const compiledIntentMap: CompiledIntentMap = {};
for (const item of compiledIntentManifest.intents) {
  compiledIntentMap[item.key] = {
    id: item.id,
    sql: item.sql,
    dialect: item.dialect
  };
}
